[Resolve]
DNSSEC=allow-downgrade
DNSOverTLS=opportunistic
#LLMNR=yes
#MulticastDNS=yes

# resolved-rs extensions (via environment in unit file):
# RESOLVED_RS_SHM=1
# RESOLVED_RS_SWR=1
# RESOLVED_RS_METRICS=127.0.0.1:9990
# RESOLVED_RS_WORKERS=0
